name: lint and pytest

on: [push, pull_request]

jobs:
  lint_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v5

      - name: ğŸ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: ğŸ› ï¸ Install build deps
        run: pip install ".[dev,lint]"

      - name: ğŸ§¹ Run black
        run: black --check --diff --color .

      - name: ğŸ§¹ Run pylint
        run: pylint .

      - name: ğŸ§ª Run pytest
        run: |
            coverage run -m pytest
            coverage report -m

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'
