name: lint and pytest

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint_pytest:
    runs-on: ubuntu-latest

    # Prevent double runs:
    # - Run push jobs only when the push is *not* part of a PR
    if: github.event_name != 'push' || github.event.pull_request == null

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v6

      - name: ğŸ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: ğŸ› ï¸ Install build deps
        run: pip install ".[dev,lint]"

      - name: ğŸ§¹ Run black
        run: black --check --diff --color .

      - name: ğŸ§¹ Run pylint
        run: pylint .

      - name: ğŸ› ï¸ Install  sqlcipher and sqlcipher3
        run: |
          sudo apt-get --no-install-recommends --no-install-suggests install libsqlcipher-dev
          pip install sqlcipher3

      - name: ğŸ§ª Run pytest with sqlcipher
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: '**/*.md'

